const cartelera = {
    "cenart": {
        "sede": "Centro Nacional de las Artes",
        "horarios": "de 11:00am a 20:00pm",
        "direccion": "Avenida Río Churubusco no. 79, esquina Calzada de Tlalpan, Col. Country Club, Alcaldía Coyoacán, C.P. 04220",
        "mapOverview": "img/calaveras/mapaCENART.JPG",
        "mapLink": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x85d1fe338dc66bd7:0x93d5104cbc6458c?source=g.page.share",
        "webLink": "https://www.cenart.gob.mx/",
        "programa": "img/calaveras/programa.pdf",
        "actividades": {
            "Laboratorios creativos": {
                "1":{
                    "nombre": "Calaquitas y ofrendas",
                    "descripcion": "Talleres para la primera infancia",
                    "tallerista": "Marianna Mendoza",
                    "sinopsis": `Los bebés experimentarán, a través de los sentidos, los objetos y alimentos presentes en los altares, que forman parte de nuestra tradición, para finalizar colocando su primera ofrenda.`,
                    "area": "Carpa de talleres",
                    "horario": "11:00, 12:00 y 13:00 horas",
                    "publico": " bebés de 0 a 24 meses, acompañados por un adulto.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "2":{
                    "nombre": "Calaqueando con PANCHA",
                    "descripcion": "Talleres para la primera infancia",
                    "tallerista": "Norma Guerrero",
                    "sinopsis": `Bebés, papás y mamás cantarán y bailarán al ritmo de sonidos ancestrales, recordando a sus seres queridos, reforzando lazos y vínculos amorosos.`,
                    "area": "Carpa de talleres",
                    "horario": "11:00, 12:00 y 13:00 horas ",
                    "publico": "bebés de 0 a 24 meses de edad, acompañados por un adulto",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "3":{
                    "nombre": "CalaCanta",
                    "descripcion": "Taller para la primera infancia",
                    "tallerista": "Greta Licona",
                    "sinopsis": `Un recorrido musical a través de canciones tradicionales, rimas, adivinanzas y danzas sobre La Flaca, en donde no quedará más que mover el esqueleto al ritmo de la música.`,
                    "area": "Carpa de talleres",
                    "horario": "11:00, 12:00, 13:00, 15:00, 16:00 y 17:00 horas.",
                    "publico": "niños y niñas de 3 a 5 años de edad.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "4":{
                    "nombre": "Calaquitas y ofrendas",
                    "descripcion": "Preescolares",
                    "tallerista": "Greta Licona",
                    "sinopsis": `Los bebés experimentarán, a través de los sentidos, los objetos y alimentos presentes en los altares partes de nuestra tradición, para finalizar colocando su primera ofrenda.`,
                    "area": "Carpa de talleres",
                    "horario": "15:00, 16:00 y 17:00 horas",
                    "publico": "niños y niñas de 3 a 5 años de edad.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "5":{
                    "nombre": "Calaqueando con PANCHA",
                    "descripcion": "Preescolares",
                    "tallerista": "Norma Guerrero",
                    "sinopsis": `Bebés, papás y mamás cantarán y bailarán al ritmo de sonidos ancestrales, recordando a sus seres queridos, reforzando lazos y vínculos amorosos.`,
                    "area": "Carpa de talleres",
                    "horario": "15:00, 16:00 y 17:00 horas.",
                    "publico": "niños y niñas de 3 a 5 años de edad.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "6":{
                    "nombre": "Los colores de La Catrina",
                    "descripcion": "Preescolares",
                    "tallerista": "Alhelí Goyce",
                    "sinopsis": `Niñas y niños, jugarán y reconocerán distintas sensaciones a través de la pintura, para dibujar con sus manos y pies una enorme Catrina, mientras cantan y bailan.`,
                    "area": "Carpa de talleres",
                    "horario": "11:00, 12:00, 13: 00, 15:00, 16:00 y 17:00 horas.",
                    "publico": "niños y niñas de 3 a 5 años de edad.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "7":{
                    "nombre": "Lotería Huasteca y Sonera",
                    "descripcion": "Talleres para la Segunda Infancia",
                    "tallerista": "Alec Dempster",
                    "sinopsis": `Niñas y niños conocerán la música tradicional mexicana, a través del juego de La Lotería, en el que, a su vez, se cantarán y formarán rimas sobre el Día de Muertos como en un gran jolgorio musical.`,
                    "area": "Carpa de talleres",
                    "horario": "11:00, 12:00, 13:00, 15:00, 16:00 y 17:00 horas.",
                    "publico": "niños de 6 a 12 años de edad.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "8":{
                    "nombre": "Somos Nahuales",
                    "descripcion": "Talleres para la Segunda infancia",
                    "tallerista": "Hasam Díaz",
                    "sinopsis": `Experimentar y explorar juegos teatrales, a través de diversas historias creadas por los mismos niños basados en las leyendas de los nahuales.`,
                    "area": "Carpa de talleres",
                    "horario": "11:00, 12:00, 13:00, 15:00, 16:00 y 17:00 horas.",
                    "publico": "niños y niñas de 6 a 12 años de edad.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "9":{
                    "nombre": "La muerte itinerante",
                    "descripcion": "Talleres para la Segunda infancia",
                    "tallerista": "Filogonio Naxin y Cristal Mora",
                    "sinopsis": `Podrán conocer y reconocer la diversidad cultural que hay en México a través de un acercamiento a las celebraciones del Día de Muertos en el pueblo mazateco. Aprenderán a hacer un grabado en linóleo, mismo que se llevarán a casa.`,
                    "area": "Carpa de talleres",
                    "horario": "11:00, 12:00, 13: 00, 15:00, 16:00 y 17:00 horas.",
                    "publico": "niños y niñas de 6 a 12 años de edad.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "10":{
                    "nombre": "Calaveritas Musicales",
                    "descripcion": "Talleres para la Segunda infancia",
                    "tallerista": "Liliana Gama y Fernando Hinojosa",
                    "sinopsis": `Los participantes conocerán, compondrán y cantarán calaveras literarias desarrollando su creatividad, su habilidad para escuchar a los demás y la emisión de su voz cantada, fortaleciendo la diversidad de su propia cultura.`,
                    "area": "Carpa de talleres",
                    "horario": " 11:00, 12:00 y 13:00 horas.",
                    "publico": "niños y niñas de 6 a 12 años de edad.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "11":{
                    "nombre": "El circo del inframundo",
                    "descripcion": "Talleres para la segunda infancia y familiar",
                    "tallerista": "Misael Nájera",
                    "sinopsis": `Taller en el que conocerán distintas artes circenses para hacer una coreografía grupal entre malabares y movimientos esqueléticos.`,
                    "area": "Carpa de talleres",
                    "horario": "11:00, 12:00, 13:00, 15:00, 16:00 y 17:00 horas.",
                    "publico": "niños y niñas de 8 a 12 años, pueden entrar acompañados de un hermano mayor.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "12":{
                    "nombre": "Máscaras de Diablos Negros",
                    "descripcion": "Talleres para adolescentes",
                    "tallerista": "Liliana Gama y Fernando Hinojosa",
                    "sinopsis": `A partir de la expresión popular de la Costa Chica de Guerrero y Oaxaca, crearemos nuestra propia máscara, para la celebración nacional del Día de Muertos.`,
                    "area": "Carpa de talleres",
                    "horario": "15:00, 16:00 y 17:00 horas",
                    "publico": "adolescentes de 13 a 17 años de edad.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "13":{
                    "nombre": "Caligramas literarios de la huesuda",
                    "descripcion": "Talleres para adolescentes",
                    "tallerista": "Jesús Urbina",
                    "sinopsis": `Se realizarán caligramas poéticos de calaveritas literarias, entrecruzando la tradición para elaborar calaveritas literarias con el uso de la poesía visual.`,
                    "area": "Carpa de talleres",
                    "horario": "11:00, 12:00, 13:00, 15:00, 16:00 y 17:00 horas.",
                    "publico": "adolescentes de 13 a 17 años de edad.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "14":{
                    "nombre": "RAP. Ritmo y poesía",
                    "descripcion": "Talleres para adolescentes",
                    "tallerista": "Danger",
                    "sinopsis": `Los niños y niñas asistentes podrán crear sus propios versos e improvisaciones al ritmo del Rap.`,
                    "area": "Carpa de talleres",
                    "horario": "11:00, 12:00, 13:00, 15:00, 16:00 y 17:00 horas.",
                    "publico": "adolescentes de 13 a 17 años de edad.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "15":{
                    "nombre": "El Break de las calacas",
                    "descripcion": "Taller grupal",
                    "tallerista": "Spin Master Crew",
                    "sinopsis": `Taller en que conocerán distintos pasos del Break para hacer una coreografía colectiva al ritmo de las calacas.`,
                    "area": "Carpa de talleres",
                    "horario": "11:00, 12:00, 13:00, 15:00, 16:00 y 17:00 horas.",
                    "publico": "niños y niñas de 10 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "16":{
                    "nombre": "Esta es mi voz",
                    "descripcion": "Talleres de participación infantil",
                    "tallerista": "Libia Ortiz",
                    "sinopsis": `Generar un espacio donde los niños, niñas y adolescentes de México puedan plasmar sus visiones del mundo de manera libre y directa, en un formato sonoro fácil de difundir en redes sociales. De forma que sus puntos de vista puedan ser tomados en cuenta en la educación, la cultura y el desarrollo del país, en colaboración con instituciones públicas educativas, sociales y culturales.`,
                    "area": "Carpa de talleres",
                    "horario": "16:00 y 17:00 horas.",
                    "publico": "niños y niñas de 7 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "17":{
                    "nombre": "Taller de origami",
                    "descripcion": "Talleres para adolescentes",
                    "tallerista": "Rodrigo Elorza",
                    "sinopsis": `Taller basado leyendas tradicionales mexicanas relacionadas con la muerte.`,
                    "area": "Carpa de talleres",
                    "horario": "12:00, 13: 00, 15:00, 16:00, 17:00 horas.",
                    "publico": "niños y niñas de 9 a 17 años",
                    "observaciones": "",
                    "delegacion": "Jalisco" ,
                },
                "18":{
                    "nombre": "Taller de Calaveras o Flores de Cempasúchil",
                    "descripcion": "Talleres para la Segunda infancia",
                    "tallerista": "Oscar Rodríguez",
                    "sinopsis": `Taller de calaveras basado en el cuento El Pato y la Muerte  Wolf Erlbruch.`,
                    "area": "",
                    "horario": "11:00, 12:00, 13: 00, 15:00 y 16:00 horas.",
                    "publico": "niños y niñas de 6 a 9 años.",
                    "observaciones": "",
                    "delegacion": "Jalisco" ,
                },
                "19":{
                    "nombre": "Taller de Papalotes en homenaje a Toledo ",
                    "descripcion": "Talleres para segunda infancia y adolescentes",
                    "tallerista": "Miriam Alvarado",
                    "sinopsis": `Taller basado en el libro La muerte, pies ligeros, del Fondo de Cultura Económica, ilustrada por Francisco Toledo.`,
                    "area": "",
                    "horario": "11:00, 12:00, 13:00, 15:00 y 16:00 horas.",
                    "publico": "niños y niñas de 6 a 17 años",
                    "observaciones": "",
                    "delegacion": "Jalisco" ,
                },
                "20":{
                    "nombre": "Taller El siguiente en la fila de títeres de calaveras",
                    "descripcion": "Talleres para segunda infancia y adolescentes",
                    "tallerista": "Fernando (triciclo)",
                    "sinopsis": `Basado en el libro de cuentos sobre la rebanada de queso (Parque Juárez de Guanajuato) de Ray Bradbury`,
                    "area": "",
                    "horario": "12:00, 13: 00, 15:00, 16:00, 17:00 horas.",
                    "publico": "niños y niñas de 6 a 17 años",
                    "observaciones": "",
                    "delegacion": "Jalisco" ,
                },
                "21":{
                    "nombre": "Taller de dulces calaveras Zacatecanas",
                    "descripcion": "Talleres para segunda infancia y adolescentes",
                    "tallerista": "María Magdalena Baltazar Ichaurregui",
                    "sinopsis": `Contribuir a mantener viva la tradición del día de muertos por medio de la participación creativa al decorar la calaveritas de azúcar  la cual podrá utilizar para adornar sus altares o como simple obsequio a sus seres queridos, proporcionándole los elementos necesarios para el desarrollo de su creatividad y personificar  su calaverita como lo son: decorado (pasta elaborada a base de azúcar glas, huevo, color vegetal y sabor propio para alimentos), lentejuelas, papel lustre, pasas, nueces, entre otros.`,
                    "area": "",
                    "horario": " 12:00, 13: 00, 15:00, 16:00, 17:00 horas",
                    "publico": "niños y niñas de 6 a 15 años",
                    "observaciones": "",
                    "delegacion": "Zacatecas" ,
                },
            },
            "Presentaciones artísticas": {
                "1":{
                    "nombre": "X∀ИT010",
                    "descripcion": "Live act audiovisual ",
                    "tallerista": "Magenta y Fabiola Larios",
                    "sinopsis": `El performance como una práctica que retoma el conocimiento ancestral a partir del pensamiento mágico. Un ritual energético con la generación de imágenes, frecuencias diseñadas a partir de sigilos y pulsos dirigidos a liberar el subconsciente. Presentación que forma parte del Festival Hello World.`,
                    "area": "Teatro de las Artes",
                    "horario": "12:00 horas.",
                    "publico": "niños y niñas de 12 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "2":{
                    "nombre": "¿Está vivo el pan de muerto?",
                    "descripcion": "Teatro",
                    "tallerista": "Cabaret Misterio",
                    "sinopsis": `Teatro Cabaret para niñas y niños, y sucesos inesperados en la vida de Soledad para conseguir amigos. Alguien se robó el pan de muerto y habrá que averiguar quién fue. Esta obra es apoyada por el Fondo Nacional para la Cultura y las Artes.`,
                    "area": "Teatro de las Artes",
                    "horario": "14:00 horas.",
                    "publico": "niñas y niños de 6 años en adelante",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "3":{
                    "nombre": "Deshuesadero Suite",
                    "descripcion": "Teatro",
                    "tallerista": "Colectivo Deshuesadero T ",
                    "sinopsis": `Una danza de cuerpos buscándose a sí mismos. Fragmentos humanos deseando ser reconocidos a través de un increíble viaje de reconstrucción. Un bello y ridículo juego de acoso, tortura y muerte. Espectáculo silente (no verbal) musical para máscaras y objetos inspirado en el tema de la desaparición forzada y tráfico humano.`,
                    "area": "Teatro de las Artes",
                    "horario": "16:00 horas..",
                    "publico": "niños y niñas de 15 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "4":{
                    "nombre": "Corazón de Plomo ",
                    "descripcion": "Teatro",
                    "tallerista": "La Sociedad de las Liebres",
                    "sinopsis": `Clara, Nicolás y Emiliano se han encerrado en el sótano de la casa de sus abuelos, pues sus papás quieren venderla. Allí contarán una gran historia para recordarlos, una donde un soldadito de una pierna emprende una gran aventura para reencontrarse con una bella bailarina. Juntos descubrirán que el recuerdo de aquellos que ya partieron permanecerá en la memoria y en las historias que vivieron juntos.`,
                    "area": "Teatro de las Artes",
                    "horario": "18:00 horas.",
                    "publico": "niños y niñas de 4 años en adelante",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "5":{
                    "nombre": "Los 400 alebrijes que no usan zapatos \n Poemas y canciones para el Día de Muertos",
                    "descripcion": "Música",
                    "tallerista": "Por Indira Isel Torres Cruz y Juanjo Castamar. Presentación artística de Alas y Raíces del estado de Colima",
                    "sinopsis": `La familia Calavera, Ratamundi y el Blues de las greñas tiesas son algunas canciones que nos compartirán Indira y Juanjo para celebrar el Día de Muertos.`,
                    "area": "Plaza de las Artes",
                    "horario": "12:00 horas.",
                    "publico": "niñas y niños de 6 años en adelante",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "6":{
                    "nombre": "Cantando y sonando del tequio al fandango",
                    "descripcion": "Música",
                    "tallerista": "Trotamundos Teatro y Media Luna ",
                    "sinopsis": `Acompaña a Trotamundos Teatro y Media Luna con sus títeres para hacer un verdadero fandango.`,
                    "area": "Plaza de las Artes",
                    "horario": "14:00 horas.",
                    "publico": "niñas y niños de 6 años en adelante",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "7":{
                    "nombre": "Los cuentos de Doña Francisca",
                    "descripcion": "Teatro de títeres",
                    "tallerista": "Compañía La Cucaracha. <br> Presentación artística de Alas y Raíces del estado de Jalisco",
                    "sinopsis": `La compañía La Cucaracha te contará a través del teatro de títeres historias de la oralidad rural alusivas al Día de Muertos.`,
                    "area": "Plaza de las Artes",
                    "horario": "16:00 horas.",
                    "publico": "todo público ",
                    "observaciones": "",
                    "delegacion": "Jalisco" ,
                },
                "8":{
                    "nombre": "Fandango del Inframundo",
                    "descripcion": "Musical de son jarocho con títeres",
                    "tallerista": "La Historia de Todxs",
                    "sinopsis": `La última bailadora de una comunidad veracruzana falleció. A la mañana siguiente de su muerte, el sonido desaparece: del viento, de los árboles, del agua. Dos niños salen a buscar el sonido perdido: poco a poco, en la selva, se encuentran con los animales y seres que conformarán el fandango del inframundo, en donde los humanos se transforman en animales, los animales en humanos.`,
                    "area": "Plaza de las Artes",
                    "horario": "18:00 horas.",
                    "publico": "niños y niñas de 6 años en adelante",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "9":{
                    "nombre": "Cantos y juegos de terror",
                    "descripcion": "Saltapatrás",
                    "tallerista": "Música con narración ",
                    "sinopsis": `Escucha las canciones de terror que trae para ti Saltapatrás, seguro te morirás de miedo al conocer sus pavorosos relatos y leyendas. `,
                    "area": "Escenario Principal",
                    "horario": "11:00 horas.",
                    "publico": "niños y niñas de 4 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "10":{
                    "nombre": "Ofrenda",
                    "descripcion": "Música fusión del mundo",
                    "tallerista": "Eblen Macari Ensamble",
                    "sinopsis": `Un canto sagrado que fusiona la música contemporánea, los sonidos ancestrales junto con raíces árabes y son jarocho en un programa especial hecho para las celebraciones de todos los santos.`,
                    "area": "Escenario Principal",
                    "horario": "13:00 horas.",
                    "publico": "niños y niñas de 6 años en adelante",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "11":{
                    "nombre": "Son Rompe Pera",
                    "descripcion": "Música con marimba ",
                    "tallerista": "",
                    "sinopsis": `Mueve tus huesitos al ritmo de su peculiar música cumbia- garage-punk.`,
                    "area": "Escenario Principal",
                    "horario": "15:00 horas.",
                    "publico": "toda la familia",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "12":{
                    "nombre": "Cuando la muerte sea rima: La Huesuda vs El Diablo ",
                    "descripcion": "Música tradicional/Controversia ",
                    "tallerista": "",
                    "sinopsis": `De dos a tres caídas con límite de tiempo, un encuentro de las mejores rimas del inframundo: en una esquina La Huesuda versando del bando de los técnicos y en la otra esquina el Diablo improvisando sus mejores fechorías. 
                    Aquí puedes participar con ellos… ¿Y tú, de qué bando eres?`,
                    "area": "Escenario Principal",
                    "horario": "17:00 horas.",
                    "publico": "toda la familia",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "13":{
                    "nombre": "Cuando yo me muera",
                    "descripcion": "Música rock ",
                    "tallerista": "Los Patita de Perro",
                    "sinopsis": `Cuando yo me muera es la canción que crearon Los Patita de Perro para homenajear y celebrar el Día de Muertos, pero no solo escucharás este sencillo, además traen mucho rock para que brinques con toda tu familia.`,
                    "area": "Escenario Principal",
                    "horario": "19:00 horas.",
                    "publico": "toda la familia",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "14":{
                    "nombre": "Monotipia. La huella única de la vida y la muerte",
                    "descripcion": "Pasacalles teatrales",
                    "tallerista": "Séptima Eleusis. Laboratorio Teatral ",
                    "sinopsis": `¿Qué huellas dejamos al paso de nuestra vida? Monotipia es una oda a eso que, dentro de nosotros nos hace saber que el arte es nuestra huella.`,
                    "area": "Áreas verdes",
                    "horario": "13:00 y 16:00 horas",
                    "publico": "toda la familia ",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "15":{
                    "nombre": "El Folk Chou",
                    "descripcion": "Pasacalles circenses",
                    "tallerista": "Cabaret Capricho \n Presentación Artística de Alas y Raíces del estado de Jalisco",
                    "sinopsis": `Propiciadas por artistas y especialistas de distintas formaciones quienes utilizan diversos juegos y técnicas para acercar a niñas, niños y adolescentes a dinámicas que generen distintas visiones y formas de responder al diario vivir.`,
                    "area": "Áreas verdes",
                    "horario": "14:00 y 18:00 horas",
                    "publico": "toda la familia ",
                    "observaciones": "",
                    "delegacion": "Jalisco" ,
                },
            },
            "Exposiciones": {
                "1":{
                    "nombre":"OFRENDA JALISCO",
                    "descripcion": "OFRENDA PROPUESTA POR ESTADO DE JALISCO",
                    "tallerista": "",
                    "sinopsis": `Ofrenda propuesta por el estado de Jalisco. (1°,2 Y 3 noviembre) `,
                    "area": "Áreas verdes en herradura",
                    "horario": "De 11:00 a 20:00 horas",
                    "publico": "infancias, público juvenil y público en general.",
                    "observaciones": "",
                    "delegacion": "Jalisco" ,
                },
                "2":{
                    "nombre":"OFRENDA OAXACA",
                    "descripcion": "OFRENDA PROPUESTA POR ESTADO DE OAXACA",
                    "tallerista": "",
                    "sinopsis": `(1°,2 Y 3 noviembre)`,
                    "area": "Área Legorreta",
                    "horario": "De 11:00 a 18:00 horas.",
                    "publico": "infancias, público juvenil y público en general.",
                    "observaciones": "",
                    "delegacion": "Oaxaca" ,
                },
                "3":{
                    "nombre":"EXPOSICIÓN El romance del maíz / hijos del maíz",
                    "descripcion": "Inauguración de nueva exposición",
                    "tallerista": "",
                    "sinopsis": `Exposición inspirada en el libro el romance del maíz que muestra a través de cinco escenarios la importancia del maíz en nuestra cultura y su importancia en el mundo. Con activación de narración y presentación artística por parte del grupo la Juglaria. `,
                    "area": "Áreas verdes",
                    "horario": "De 11:00 a 18:00 horas.",
                    "publico": "infancias, público juvenil y público en general.",
                    "observaciones": "Áreas verdes",
                    "delegacion": "" ,
                },
            },
            "Narraciones orales": {
                "1":{
                    "nombre": "A la cuenta del reloj, vayamos al mundo de los muertos",
                    "descripcion": "Narración oral",
                    "tallerista": "Ángel Aranda",
                    "sinopsis": `Existen caminos llenos de flores, amarillas y naranjas, que nos lleven al inmenso sol, existen caminos, debajo de la tierra, que serán guiados por seres espirituales que nos acompañen de retorno al Mictlán, pero también existen aquí en mi recámara, historias y leyendas que me recuerdan que El Coco, viene por nosotros y que debajo de mi cama, viven los peores fantasmas y monstruos que me quitan el sueño. Narración inspirada en la historia de Benito, un niño como tú, que no puede dormir por culpa de los relatos que hoy te quiero contar.`,
                    "area": "Foro de las Artes",
                    "horario": "11:00 horas.",
                    "publico": "niñas y niños de 3 a 6 años",
                    "observaciones": "CUPO LIMITADO (Sujeto a 90 localidades)",
                    "delegacion": "" ,
                },
                "2":{
                    "nombre": "De muertos, calacas y otros finados",
                    "descripcion": "Narración oral del estado de Colimal",
                    "tallerista": "Candy Jiménez, Francisco Jiménez y David Alva. \n Responsable: Víctor Chi.",
                    "sinopsis": `Espectáculo de narración oral escénica basado en relatos del México campesino que fincan su imaginario en las raíces prehispánicas de nuestro país.
                    El espectáculo va acompañado de música con instrumentos prehispánicos en vivo.
                    Los relatos son narrados por Toribio, un niño travieso, pero, muy avispado, la tía Rosa, mujer que siempre anda medio atolondrada y Pancho Chencho, el tío cuentero del pequeño Toribio, quienes, a través de sus relatos, van hilando una trama con un inesperado final en donde, la muerte, juega el papel principal.`,
                    "area": "Foro de las Artes",
                    "horario": "13:00 horas.",
                    "publico": "niñas y niños de 8 años en adelante",
                    "observaciones": "CUPO LIMITADO (Sujeto a 90 localidades)",
                    "delegacion": "" ,
                },
                "3":{
                    "nombre": "Cantos y cuentos, ofrendas a los muertos",
                    "descripcion": "Narración oral",
                    "tallerista": "Mireya González",
                    "sinopsis": `Narración Escénica Musical interpretada por la bruja, personaje protagónico del son jarocho tradicional de Veracruz. Ella nos contará leyendas e historias mexicanas de Día de Muertos, entre cantos, bailes, ritmos y fiesta conoceremos más de nuestra cultura, tradiciones y costumbres.`,
                    "area": "Foro de las Artes",
                    "horario": "15:00 horas.",
                    "publico": "niñas y niños de 8 años en adelante.",
                    "observaciones": "CUPO LIMITADO (Sujeto a 90 localidades)",
                    "delegacion": "" ,
                },
                "4":{
                    "nombre": "Historias de calacas, vainilla y altares",
                    "descripcion": "Narración oral",
                    "tallerista": "Aníbal Hoyos",
                    "sinopsis": `En Papantla todo vuela ¡Incluso los altares! Y esto lo vemos al visitar las casas de los pueblos donde todavía son amarrados de las vigas para que no toquen el piso y de esta forma servir como conexión entre nuestro mundo y el del más allá. Es ahí, en la ofrenda donde se esconden las historias más entrañables del Día de Muertos. Por desgracia, mucha gente empieza a olvidar los rituales, las reglas y lo asombroso de estas fechas, por ese motivo, El Puxko (un volador totonaco) sale de la tumba para acompañarnos, con sus leyendas, máscaras y bailes, en un recorrido por las creencias de la región referentes al Día de Muertos (O Ninin, como se le llama en totonaco) y los hechos sobrenaturales acontecidos en su pueblo que validan tales supersticiones. Y como en la sierra del Totonacapan se tiene la idea de un mundo donde descansan las criaturas como los chaneques, los encantos y los espíritus de los muertos, el Puxquito aprovecha para advertirnos, con historias de tradición oral, sobre esas fechas de noviembre donde las puertas de ese mundo se abren para engañar a más de un inocente.`,
                    "area": "Foro de las Artes",
                    "horario": "17:00 horas.",
                    "publico": "niñas y niños de 8 años en adelante.",
                    "observaciones": "CUPO LIMITADO (Sujeto a 90 localidades)",
                    "delegacion": "" ,
                },
                "5":{
                    "nombre": "Muertitos de palabra",
                    "descripcion": "Narración oral",
                    "tallerista": "Lidia Zaragoza",
                    "sinopsis": `Relatos de muertos, aparecidos y una huesuda traviesa.`,
                    "area": "CARPA 1 (CUCHILLA) del CENART  ",
                    "horario": "12:00 horas.",
                    "publico": "niñas y niños de 6 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "6":{
                    "nombre": "Narraciones y tradición oral de Jalisco",
                    "descripcion": "Narración oral",
                    "tallerista": "Gahdiel Andrade",
                    "sinopsis": `Gahdiel Andrade explicará el significado de cada uno de los elementos que integran la ofrenda y narrará historias relativas a la celebración de Día de Muertos.`,
                    "area": "CARPA 1 (CUCHILLA) del CENART",
                    "horario": "13:00 horas.",
                    "publico": "niñas y niños de 6 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "7":{
                    "nombre": "Historias de calacas, vainilla y altares",
                    "descripcion": "Narración oral",
                    "tallerista": "Aníbal Hoyos",
                    "sinopsis": `En Papantla todo vuela ¡Incluso los altares! Y esto lo vemos al visitar las casas de los pueblos donde todavía son amarrados de las vigas para que no toquen el piso y de esta forma servir como conexión entre nuestro mundo y el del más allá. Es ahí, en la ofrenda donde se esconden las historias más entrañables del Día de Muertos. Por desgracia, mucha gente empieza a olvidar los rituales, las reglas y lo asombroso de estas fechas, por ese motivo, El Puxko (un volador totonaco) sale de la tumba para acompañarnos, con sus leyendas, máscaras y bailes, en un recorrido por las creencias de la región referentes al Día de Muertos (O Ninin, como se le llama en totonaco) y los hechos sobrenaturales acontecidos en su pueblo que validan tales supersticiones. Y como en la sierra del Totonacapan se tiene la idea de un mundo donde descansan las criaturas como los chaneques, los encantos y los espíritus de los muertos, el Puxquito aprovecha para advertirnos, con historias de tradición oral, sobre esas fechas de noviembre donde las puertas de ese mundo se abren para engañar a más de un inocente.`,
                    "area": "CARPA 1 (CUCHILLA) del CENART",
                    "horario": "14:00 horas.",
                    "publico": "niñas y niños de 8 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "8":{
                    "nombre": "Narraciones y tradición oral de Jalisco",
                    "descripcion": "Narración oral",
                    "tallerista": "Teresa Figueroa",
                    "sinopsis": `Teresa Figueroa explicará el significado de cada uno de los elementos que integran la ofrenda y narrará historias relativas a la celebración de Día de Muertos.`,
                    "area": "CARPA 1 (CUCHILLA) del CENART",
                    "horario": "15:00 horas.",
                    "publico": "niñas y niños de 8 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "9":{
                    "nombre": "Neto el esqueleto",
                    "descripcion": "Narración oral",
                    "tallerista": "Raúl Pérez Buendía",
                    "sinopsis": `Un viaje al Mictlán para acompañar en esta aventura a Neto.`,
                    "area": "CARPA 1 (CUCHILLA) del CENART",
                    "horario": "16:00 horas.",
                    "publico": "niñas y niños de 3 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "10":{
                    "nombre": "Narraciones y tradición oral de Jalisco",
                    "descripcion": "Narración oral",
                    "tallerista": "María Tránsito Campechano",
                    "sinopsis": `María Tránsito Campechano explicará el significado de cada uno de los elementos que integran la ofrenda y narrará historias relativas a la celebración de Día de Muertos.`,
                    "area": "CARPA 2 (CAÑADA) del CENART",
                    "horario": "12:00 horas.",
                    "publico": "niñas y niños de 6 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "11":{
                    "nombre": "Cantos y cuentos, ofrendas a los muertos",
                    "descripcion": "Narración oral",
                    "tallerista": "Mireya González",
                    "sinopsis": `Narración Escénica Musical interpretada por la bruja, personaje protagónico del son jarocho tradicional de Veracruz. Ella nos contará leyendas e historias mexicanas de Día de Muertos, entre cantos, bailes, ritmos y fiesta conoceremos más de nuestra cultura, tradiciones y costumbres.`,
                    "area": "CARPA 2 (CAÑADA) del CENART",
                    "horario": "13:00 horas.",
                    "publico": "niñas y niños de 6 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "12":{
                    "nombre": "La muerte, el demonio, el catrín y la dama.<br> Cuentos de puro susto",
                    "descripcion": "Narración oral",
                    "tallerista": "Gerardo Méndez",
                    "sinopsis": `Ante la presencia de las nuevas tecnologías a las que los jóvenes y niños de nuestro país se enfrentan cada día han olvidado algunas de las tradiciones más importantes de México.
                    Con esta propuesta queremos apoyar a las familias y educadores a sensibilizar a las nuevas generaciones, y aprovechar este espectáculo de narración oral para aproximar de una manera lúdica a los niños y niñas a la tradicional festividad del Día de Muertos.`,
                    "area": "CARPA 2 (CAÑADA) del CENART",
                    "horario": "14:00 horas.",
                    "publico": "niñas y niños de 6 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "13":{
                    "nombre": "La muerte canta",
                    "descripcion": "Narración oral",
                    "tallerista": "Itzel Tapia",
                    "sinopsis": `Angelina nos cuenta cómo festejan en su pueblo la Navidad en su particular modo de contarlo contando y sonando.
                    Poesía, leyendas y canciones en torno a la muerte. / Narración con música para Día de Muertos.
                    Una china poblana viene de ultratumba a compartir las voces de Nezahualcóyotl, Sor Juana Inés de la Cruz, Chava Flores, lírica infantil, leyenda del esqueleto volador. Canciones y leyendas de dominio popular. 
                    Historias y cantos de Navidad presentados por una mujer Rarámuri.`,
                    "area": "CARPA 2 (CAÑADA) del CENART",
                    "horario": "15:00 horas.",
                    "publico": "niñas y niños de 6 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "14":{
                    "nombre": "¡Anda, anda!<br> Que la calaca te alcanza",
                    "descripcion": "Narración oral",
                    "tallerista": "Ángel Aranda",
                    "sinopsis": `Cuentan que unos viven tanto que se olvidan de la muerte, cuentan que otros mueren tan pronto que regresan a la vida en historias… 
                    Narración inspirada en historias donde la flaca, viene por todos aquellos que no festejan ni ponen un pedacito de pan en el altar. Historias que, en días como hoy, te llevarán a dar un viaje hacia el Mictlán, lugar que habitan los que se ponen a contar, para ser recordados una vez más.
                    Sesión inspirada en los relatos de: <br>
                    - El viaje a Mictlán / Víctor José Palacios <br>
                    - El Pato y la Muerte / Wolf Erlbruch <br>
                    - Francisca y la Muerte / Onelio Jorge Cardoso  
                    `,
                    "area": "CARPA 2 (CAÑADA) del CENART",
                    "horario": "16:00 horas.",
                    "publico": "adolescentes",
                    "observaciones": "",
                    "delegacion": "" ,
                },
            },
        },
        "videos":{
            "1":{
                "nombre": "Feria de las calacas 2018",
                "url": "https://www.youtube.com/watch?v=yPXUyucEOMg",
            },
            "2":{
                "nombre": "XVI Feria de las Calacas de Alas y Raíces",
                "url": "https://www.youtube.com/watch?v=FpzX8JpTHLI",
            },
            "3":{
                "nombre": "Feria de las calacas 2015",
                "url": "https://www.youtube.com/watch?v=qbKAQHzK8aw",
            },
        }
    },
    "pinos": {
        "sede": "Los Pinos",
        "horarios": "de 12:00pm a 17:00pm",
        "direccion": "Parque Lira s/n, Bosque de Chapultepec I Secc, Alcaldía Miguel Hidalgo, C.P. 11850",
        "mapOverview": "img/calaveras/mapaPinos.JPG",
        "mapLink": "https://www.google.com/maps/place/Los+Pinos/@19.4156636,-99.1934009,17z/data=!3m1!4b1!4m5!3m4!1s0x85d201e2607a9651:0xe8b1edf657b2032f!8m2!3d19.4156586!4d-99.1912122?shorturl=1",
        "webLink": "https://www.lospinosparatodos.com/",
        "programa": "img/calaveras/programa.pdf",
        "actividades": {
            "Laboratorios creativos": {
                "1":{
                    "nombre": "Al son que me toquen ",
                    "descripcion": "Taller para Preescolares",
                    "tallerista": "Lilian Cantante",
                    "sinopsis": `Baila y juega con ritmos del mundo, cantados por la Soprano Lilian, en un espacio creado para movernos.`,
                    "area": "Cabaña 3",
                    "horario": "13:00, 16:00 y 17:00 horas",
                    "publico": "niños y niñas de 3 a 5 años de edad",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "2":{
                    "nombre": "Canciones de cuna",
                    "descripcion": "Taller para Lactantes y Maternales",
                    "tallerista": "Lilian Cantante",
                    "sinopsis": `Vivamos la tradición de los cantos de cuna con la Soprano Lilian, entre dinámicas dirigidas, apapachos y sonrisas.`,
                    "area": "Cabaña 3",
                    "horario": "14:00 horas",
                    "publico": "bebés de 0 a 24 meses de edad, acompañados por un adulto",
                    "observaciones": "",
                    "delegacion": "" 
                },
                "3":{
                    "nombre": "Vamos a llorarle y bailarle a la muerte",
                    "descripcion": "Taller para la segunda infancia",
                    "tallerista": "Natalia Cárdenas",
                    "sinopsis": `Jugamos a ser plañideras y a llevar, desde nuestra casa al panteón, a nuestros muertos, bailando al ritmo de distintas versiones musicales de La Llorona.`,
                    "area": "Cabaña 3",
                    "horario": "13:00, 14:00, 16:00 y 17:00 horas.",
                    "publico": "niños de entre 6 a 10 años de edad.",
                    "observaciones": "",
                    "delegacion": "" 
                },
                "4":{
                    "nombre": "Los Colores de la Muerte en México",
                    "descripcion": "Taller para la Segunda infancia",
                    "tallerista": "Rosy Pelcastre",
                    "sinopsis": `Cada participante será guiado, entre cuentos, leyendas y anécdotas de la muerte, para que con su ingenio y creatividad realice una composición de inspiración propia, en la que involucre elementos que contengan colores alusivos a la muerte en México.`,
                    "area": "Cabaña 3",
                    "horario": "13:00, 14:00, 16:00 y 17:00 horas.",
                    "publico": "niños de entre 8 a 12 años.",
                    "observaciones": "",
                    "delegacion": "" 
                },
                "5":{
                    "nombre": "Noyohualli Notlaneci. Tendedero poético",
                    "descripcion": "Talleres para Adolescentes",
                    "tallerista": "Karloz Atl",
                    "sinopsis": `Aprenderemos a crear calaveritas literarias, para jugar con el lenguaje y la muerte, de forma divertida, celebrando a nuestros vivos y difuntos.`,
                    "area": "Cabaña 3",
                    "horario": "13:00, 14:00, 16:00 y 17:00 horas.",
                    "publico": "adolescentes de entre 13 a 17 años de edad",
                    "observaciones": "",
                    "delegacion": "" 
                },
                "6":{
                    "nombre": "Exploración escénica. ¿De qué color son los dolores?",
                    "descripcion": "Talleres para Adolescentes",
                    "tallerista": "Diego Montero",
                    "sinopsis": `El taller busca acercar a jóvenes audiencias al Teatro como una herramienta de introspección humana. Generar un encuentro de satisfacción y aprendizaje al crear un espacio para juegos corporales/escénicos a través de la expresión de pequeñas anécdotas relacionadas con la muerte y la sensación de pérdida, no como un hecho doloroso, sino como encuentro de sensaciones, colores y expresiones que puedan plasmarse en el cuerpo y en papel. Lo anterior vinculado a temáticas de su interés (aficiones, gustos, oficios y/o problemáticas de vida). Un espacio entre pares que fomente el pensamiento, reflexión y goce.`,
                    "area": "Cabaña 3",
                    "horario": "13:00, 14:00, 16:00 y 17:00 horas.",
                    "publico": "adolescentes de 13 a 17 años de edad.",
                    "observaciones": "",
                    "delegacion": "" 
                },
                "7":{
                    "nombre": "Taller de Zompantli",
                    "descripcion": "Talleres para Adolescentes",
                    "tallerista": "Osvaldo Ruelas Ramírez",
                    "sinopsis": `Los niños aprenderán la tradición de algunas culturas precolombinas del antiguo México, haciendo altares con la base decorada con cráneos.`,
                    "area": "Cabaña 3",
                    "horario": "13:00, 14:00, 16:00 y 17:00 horas.",
                    "publico": "adolescentes de 13 a 17 años.",
                    "observaciones": "",
                    "delegacion": "Guanajuato" 
                },
                "8":{
                    "nombre": "Choo- baak. Limpia de hueso",
                    "descripcion": "Taller para la segunda infancia",
                    "tallerista": "Bernabé Rosado López",
                    "sinopsis": `Para recrear una tradición ancestral de Campeche, la limpia de huesos de Pomuch, haremos un esqueleto en plastilina, con una manta con la que se envuelve (vestimenta). Esto se deposita en un osario (contenedor de madera). Esta es una forma de expresar el amor hacia el familiar fallecido, es un encuentro entre los que se fueron y los que estamos aquí vivos.`,
                    "area": "Cabaña 3",
                    "horario": "12:00, 13:00, 15:00, 16:00 horas",
                    "publico": "adolescentes de 6 a 12 años.",
                    "observaciones": "",
                    "delegacion": "Campeche" 
                },
                "9":{
                    "nombre": "Elaboración de pan de muerto",
                    "descripcion": "Talleres para Adolescentes",
                    "tallerista": "Manuel Caamal Cazan",
                    "sinopsis": `Taller enfocado a niños en donde aprenderán la elaboración del pan de muerto de la forma tradicional, a través de la pasta fría para modelar.
                    El objetivo es que los niños conozcan el significado de porqué la forma que tiene y porqué forma parte de la ofrenda hacia nuestros difuntos.`,
                    "area": "Cabaña 3",
                    "horario": "12:00, 13:00, 15:00, 16:00 horas",
                    "publico": "adolescentes de 13 a 17 años.",
                    "observaciones": "",
                    "delegacion": "Campeche" 
                },
                "10":{
                    "nombre": "Zapateado y jaranas",
                    "descripcion": "Talleres para Adolescentes",
                    "tallerista": "Maestros de zapateado",
                    "sinopsis": `Taller donde conocerán los ritmos de Veracruz, para cantarle a los muertos al ritmo del zapateado y las jaranas.`,
                    "area": "Cabaña 3",
                    "horario": "12:00, 13:00, 15:00, 16:00 horas",
                    "publico": "adolescentes de 13 a 17 años.",
                    "observaciones": "",
                    "delegacion": "Veracruz" 
                },
            },
            "Presentaciones artísticas": {
                "1":{
                    "nombre": "Algo sobres las leyes de la gravitación",
                    "descripcion": "Teatro",
                    "tallerista": "La Caja de Teatro",
                    "sinopsis": `Analogía entre las leyes de la física y la búsqueda de la libertad del ser humano. 
                    Las leyes de la física están ahí, como conjuros, para recordarnos como un hechizo que los cuerpos transitan por el mundo, y que nosotros somos apenas una partícula en el universo capaz de desplazarse.
                    `,
                    "area": "Hondonada.",
                    "horario": "12:00 horas.",
                    "publico": "niñas y niños de 12 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "2":{
                    "nombre": "Hermanas García",
                    "descripcion": "Música",
                    "tallerista": "Hermanas García",
                    "sinopsis": `Desde Ometepec, Guerrero, las Hermanas García traen un repertorio exclusivamente para niñas y niños celebrando el Día de Muertos.`,
                    "area": "Hondonada.",
                    "horario": "13:30 horas.",
                    "publico": "niñas y niños de 6 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "3":{
                    "nombre": "Niñas Trovadoras de la Orquesta Típica Infantil y Juvenil Alas y Raíces Yucatán. Presentación Artística de Alas y Raíces del estado de Yucatán",
                    "descripcion": "Música",
                    "tallerista": "Niñas Trovadoras",
                    "sinopsis": `Las Niñas Trovadoras es una agrupación musical conformada actualmente por cuatro adolescentes entre 12 y 14 años, integrantes de la Orquesta Típica Infantil y Juvenil Alas y Raíces Yucatán, las cuales ejecutan un repertorio representativo de la canción tradicional yucateca, con el objetivo de preservarla y difundirla entre las nuevas generaciones.`,
                    "area": "Hondonada.",
                    "horario": "15:00 horas.",
                    "publico": "toda la familia",
                    "observaciones": "",
                    "delegacion": "Yucatán" ,
                },
                "4":{
                    "nombre": "Fandango: Un ritual de Veracruz",
                    "descripcion": "Música",
                    "tallerista": "Grupo infantil de Son jarocho de Veracruz. Presentación Artística de Alas y Raíces del estado de Veracruz",
                    "sinopsis": `Interpretará sones tradicionales de la región de los Tuxtlas, Veracruz: La Bamba, Colas, Butaquito, La Guacamaya, El Pájaro CU, La Candela, Los Enanitos. Se tocarán instrumentos tradicionales como: jaranas y guitarras de son.`,
                    "area": "Hondonada.",
                    "horario": "16:30 horas.",
                    "publico": "toda la familia",
                    "observaciones": "",
                    "delegacion": "Veracruz" ,
                },
                "5":{
                    "nombre": "Muertos… ¡pero de gusto!",
                    "descripcion": "Música",
                    "tallerista": "Itacate de Cuentos",
                    "sinopsis": `Concierto de Cuentos, Cantos y Encantos sobre la tradición de Día de Muertos en México.`,
                    "area": "Hondonada.",
                    "horario": "18:00 horas.",
                    "publico": "toda la familia",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "6":{
                    "nombre": "Rebumbio de las Calaveras",
                    "descripcion": "Música",
                    "tallerista": "Pasacalles",
                    "sinopsis": `Acompaña a los veinticinco personajes de Guadalupe Posada y los músicos de la banda de viento, ponen a bailar a vivos y a muertos.`,
                    "area": "Áreas verdes.",
                    "horario": "14:00 y 16:00 horas.",
                    "publico": "toda la familia",
                    "observaciones": "",
                    "delegacion": "" ,
                }
            },
            "Exposiciones": {
                "1":{
                    "nombre":"Ofrenda Alas y Raíces",
                    "descripcion": "Ofrenda inspirada en el tema de muerte y olvido",
                    "tallerista": "Alas y Raíces",
                    "sinopsis": `Ofrenda inspirada en la idea que sólo muere lo que cae en el olvido.`,
                    "area": "Salón López Mateos.",
                    "horario": "De 11:00 a 18:00 horas.",
                    "publico": "infancias, público juvenil y público en general.",
                    "observaciones": "Informes: 55 4155 0200 ext. 2412",
                    "delegacion": "" ,
                },
               
            },
            "Narraciones orales": {
                "1":{
                    "nombre": "El gusto por el susto ",
                    "descripcion": "Narración oral",
                    "tallerista": "Alma Rosa Rivera",
                    "sinopsis": `Cuentos de falso miedo para niños pequeños.`,
                    "area": "Jardín de la fuente frente al Espacio de lectura del CC Los Pinos",
                    "horario": "13:00 horas.",
                    "publico": "niñas y niños de 3 a 6 años",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "2":{
                    "nombre": "MEZTLI ",
                    "descripcion": "Narración teatralizada con títeres",
                    "tallerista": "Gisel Casas",
                    "sinopsis": `Meztli es una niña de Oaxaca que pierde a su mamá. Un Día de Muertos comienza a recordarla y, entre sueños, recorrerá el Mictlán junto a un colibrí y una mariposa para descubrir el significado de la vida y la muerte.`,
                    "area": "Jardín de la fuente frente al Espacio de lectura del CC Los Pinos",
                    "horario": "12:00 horas.",
                    "publico": "niñas y niños de 6 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "3":{
                    "nombre": "El petate del muerto ",
                    "descripcion": "Narración oral",
                    "tallerista": "Fermín Camacho",
                    "sinopsis": `Cuentos para muertos y vivos de nuestro pueblo.`,
                    "area": "Jardín de la fuente frente al Espacio de lectura del CC Los Pinos",
                    "horario": "14:00 horas.",
                    "publico": "niñas y niños de 6 a 12 años.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "4":{
                    "nombre": "La calavera indiscreta y el cuarteto de los torsos huecos",
                    "descripcion": "Narración teatralizada  ",
                    "tallerista": "Gisel Casas",
                    "sinopsis": `La calavera indiscreta decide narrar relatos de seres fantásticos al cuarteto de los torsos huecos, juntos imaginan historias que relatan las raíces de la tradición de Día de Muertos. Finalmente, el cuarteto decide festejar las narraciones bailando al ritmo de la Marimba.`,
                    "area": "Casita del árbol del CC Los Pinos.",
                    "horario": "14:00 horas.",
                    "publico": "niñas y niños de 6 a 12 años",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "5":{
                    "nombre": "El Alacrán Diabólico y otros cuentos de susto",
                    "descripcion": "Narración oral",
                    "tallerista": "Vivianne Thirion",
                    "sinopsis": `Cuentos y leyendas de tradición.`,
                    "area": "Casita del árbol del CC Los Pinos.",
                    "horario": "15:00 horas.",
                    "publico": "niñas y niños de 8 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "6":{
                    "nombre": "Historias de muertos y aparecidos",
                    "descripcion": "Narración oral",
                    "tallerista": "Gloria Ávila Dorador",
                    "sinopsis": `Sinopsis: ¿Sabes qué le pasó al señor que no puso la ofrenda? Criaturas que se comen a los niños, duendes que se roban el alma de las muchachas y otras historias que te pondrán los pelos de punta.`,
                    "area": "Casita del árbol del CC Los Pinos.",
                    "horario": "16:00 horas.",
                    "publico": "niñas y niños de 8 años en adelante ",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "7":{
                    "nombre": "El camino de papalotes",
                    "descripcion": "Narración oral",
                    "tallerista": "Giovanna Cavasola",
                    "sinopsis": `Muchas son las tradiciones y ofrendas para recibir a los seres queridos que se nos han adelantado. En Oaxaca, nos enseñó el Maestro Francisco Toledo, se vuelan papalotes para que encuentren el camino a la ofrenda y vengan a convivir con nosotros ese día. Este espectáculo de cuentos quiere recordar, de manera amena, algunas de estas tradiciones, así como proponer al público familiar, historias de los personajes que nos visitan en días de muertos según los relatos de tradición oral de varias regiones de México y otros países.`,
                    "area": "Nicho verde de la hondonada del CC Los Pinos.",
                    "horario": "14:00 horas.",
                    "publico": "niñas y niños de 8 años en adelante  ",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "8":{
                    "nombre": "Danza en tierra de nadie",
                    "descripcion": "Danza butoh ",
                    "tallerista": "Espartaco Martínez",
                    "sinopsis": `Este performance de danza butoh intenta ser un homenaje a la gente que hoy, sea aquí en la frontera sur o norte, sea en las costas del mediterráneo, en alguna frontera, deja su sangre en pos de la sobrevivencia negada.`,
                    "area": "Nicho verde de la hondonada del CC Los Pinos.",
                    "horario": "16:00 horas.",
                    "publico": "niñas y niños de 10 años en adelante",
                    "observaciones": "",
                    "delegacion": "" ,
                },

            },
        },
        "videos":{
            "1":{
                "nombre": "Feria de las calacas 2018",
                "url": "https://www.youtube.com/watch?v=yPXUyucEOMg",
            },
            "2":{
                "nombre": "XVI Feria de las Calacas de Alas y Raíces",
                "url": "https://www.youtube.com/watch?v=FpzX8JpTHLI",
            },
            "3":{
                "nombre": "Feria de las calacas 2015",
                "url": "https://www.youtube.com/watch?v=qbKAQHzK8aw",
            },
        }
    },
    "central": {
        "sede": "Central de abasto",
        "horarios": "de 12:00pm a 17:00pm",
        "direccion": "Av. Canal de Río Churubusco s/n Esq. Canal de Apatlaco, Col Central de Abasto, Alcaldía Iztapalapa, C.P. 09040",
        "mapOverview": "img/calaveras/mapaCentral.JPG",
        "mapLink": "https://www.google.com/maps/place/Central+de+abasto+CDMX/@19.373979,-99.09053,16z/data=!4m5!3m4!1s0x0:0xcaea41de1a034b00!8m2!3d19.3739788!4d-99.0905297?hl=es-ES",
        "webLink": "https://ficeda.com.mx/",
        "programa": "img/calaveras/programa.pdf",
        "actividades": {
            "Laboratorios creativos": {
                "1":{
                    "nombre": "\"Hay que engañar a la muerte\" ",
                    "descripcion": "Taller para la segunda infancia",
                    "tallerista": "Lupita García",
                    "sinopsis": `A partir de la lectura en voz alta del cuento “Francisca y La Muerte”, 
                                Onelio Jorge Cardoso, niñas y niños dialogarán sobre la muerte y las ausencias. 
                                Mediante un juego de representación, podrán dialogar sobre las distintas formas en las 
                                que los mexicanos pensamos y nombramos a la muerte y escribirán cartas a sus seres 
                                fallecidos para ponerlas en el altar.`,
                    "area": "Carpas en canchas",
                    "horario": "12:00, 13:00, 15:00 y 16:00 horas",
                    "publico": "niños y niñas de 8 a 12 años de edad",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "2":{
                    "nombre": "\"Calacas acartonadas\" ",
                    "descripcion": "Taller para la segunda infancia",
                    "tallerista": "Maai Ortíz",
                    "sinopsis": `Niñas y niños, conocerán la tradición de la cartonería en México, para 
                                 elaborar su propia máscara de Día de Muertos, al estilo de distintos pueblos 
                                 mexicanos. `,
                    "area": "Carpas en canchas",
                    "horario": "12:00, 13:00, 15:00 y 16:00 horas",
                    "publico": "niños y niñas de 8 a 12 años de edad",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "3":{
                    "nombre": "\"Calacas y esqueletos\" ",
                    "descripcion": "Taller para la segunda infancia",
                    "tallerista": "Julia Arnaut",
                    "sinopsis": `En este taller vamos a imaginar cómo se mueve cada uno de los huesos que 
                                 tenemos en el cuerpo. ¿Nos movemos a la misma velocidad que nuestra mamá? 
                                 ¿Cómo se movería mi abuelita si estuviera aquí? En este taller, crearemos 
                                 personajes divertidos a partir del movimiento y sus distintas formas de moverse. 
                                 ¿Cómo cambian esos estados de ánimo la forma en que nuestro esqueleto se mueve?, 
                                 ¿cómo se moverán nuestros muertos, que vienen a visitarnos en estas fechas?`,
                    "area": "Carpas en canchas",
                    "horario": "12:00, 13:00, 15:00 y 16:00 horas",
                    "publico": "niños y niñas de 8 a 12 años de edad",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "4":{
                    "nombre": "\"Rap Intercultural\" ",
                    "descripcion": "Taller para Adolescentes",
                    "tallerista": "Sergio Ferrer",
                    "sinopsis": `Taller en el que podrán crear sus propios versos e improvisaciones al ritmo del Rap.`,
                    "area": "Carpas en canchas",
                    "horario": "12:00, 13:00, 15:00 y 16:00 horas",
                    "publico": "adolescentes de 13 a 17 años de edad.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "5":{
                    "nombre": "\"Esta es mi voz\" ",
                    "descripcion": "Taller de participación infantil",
                    "tallerista": "Libia Ortiz",
                    "sinopsis": `Generar un espacio donde los niños, niñas y adolescentes de México puedan plasmar 
                                 sus visiones del mundo de manera libre y directa, en un formato sonoro fácil de 
                                 difundir en redes sociales. De forma que sus puntos de vista puedan ser tomados en 
                                 cuenta en la educación, la cultura y el desarrollo del país, en colaboración con 
                                 instituciones públicas educativas, sociales y culturales.`,
                    "area": "Carpas en canchas",
                    "horario": "11:00, 12:00 y 13:00 horas",
                    "publico": "Más de 7 años de edad.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
            },
            "Presentaciones artísticas": {
                "1":{
                    "nombre": "\"Puppets de Canal Once\" ",
                    "descripcion": "Presentación de Canal Once",
                    "tallerista": "",
                    "sinopsis": ``,
                    "area": "Escenario Principal",
                    "horario": "10:00 horas",
                    "publico": "Para toda la familia.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "2":{
                    "nombre": "\"Cuando la muerte sea rima: El esqueleto vs La bruja\" ",
                    "descripcion": "Música tradicional/Controversia",
                    "tallerista": "",
                    "sinopsis": `De dos a tres caídas con límite de tiempo, una batalla épica de versos improvisados,
                                 representando al bando de los técnicos, el más flaco del inframundo, el más ligero con 
                                 las rimas El Esqueleto y en la otra esquina la temida por todos que hasta su risa asusta 
                                 al más valiente La Bruja del bando de los rudos.
                                 Aquí puedes participar con ellos… ¿Y tú, de qué bando eres?`,
                    "area": "Escenario Principal",
                    "horario": "12:00 horas",
                    "publico": "Para toda la familia.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "3":{
                    "nombre": "\"Artemio en-Canto de muertos\" ",
                    "descripcion": "Música con narración",
                    "tallerista": "Puro Canto Puro Cuento",
                    "sinopsis": `¿Dónde te encuentras, Abuelo?, se preguntaba Artemio esa mañana. No encontró respuesta 
                                 pronta y por el contrario si halló a su abuela Teresa, que andaba paseando por el jardín 
                                 de la casa. Doña Tere y Artemio, se unen en “Artemio en- Canto de Muertos” para buscar a 
                                 Don Chava, y saber qué ha sucedido con él y por qué se ha ausentado de la vida de ellos.`,
                    "area": "Escenario Principal",
                    "horario": "14:00 horas",
                    "publico": "A partir de 2 años de edad.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "4":{
                    "nombre": "\"Con jaranas y tarimas van las calacas y catrinas\" ",
                    "descripcion": "Música son jarocho",
                    "tallerista": "Kumaltik",
                    "sinopsis": `Por medio de los Sones Jarochos el grupo Kumaltik creará un fandango para toda la familia 
                                 en donde festejamos a nuestros muertos con bella poesía campirana acompañada por los virtuosos 
                                 ritmos jarochos, la fuerza del zapateado tradicional y la energía de la improvisación instrumental.`,
                    "area": "Escenario Principal",
                    "horario": "16:00 horas",
                    "publico": "Para toda la familia.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "5":{
                    "nombre": "\"Cajas mágicas\" ",
                    "descripcion": "Laboratorio. Mecánica en Miniatura",
                    "tallerista": "",
                    "sinopsis": `Microhistorias basadas en en hechos, relatos y leyendas del folclor popular que se caracterizan 
                                 por la delgada línea entre la realidad y el mito que han estimulado la imaginación y la fantasía 
                                 de varias generaciones.`,
                    "area": "Áreas verdes",
                    "horario": "De 12:00 a 16:00 horas.",
                    "publico": "Para toda la familia.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
            },
            "Exposiciones": {
                "1":{
                    "nombre": "\"Vendedora de frutas\" ",
                    "descripcion": "Ofrenda inspirada en la obra \“LA VENDEDORA DE FRUTAS\”",
                    "tallerista": "Mónica Torres",
                    "sinopsis": `Ofrenda inspirada en la obra La vendedora de frutas, de Olga Costa, que muestra la riqueza y 
                                 diversidad de la gastronomía mexicana.`,
                    "area": "Área de canchas y bajo puente.",
                    "horario": "De 11:00 a 18:00 horas.",
                    "publico": "Para Infancias, público juvenil y público en general.",
                    "observaciones": "Informes: 55 5600 6248",
                    "delegacion": "" ,
                },
            },
            "Narraciones orales": {
                "1":{
                    "nombre": "\"Los cuentos de la dulce calaverita de azúcar\" ",
                    "descripcion": "Narración oral",
                    "tallerista": "Ana Cristina Ortega",
                    "sinopsis": `Desde el más allá viene la dulce calaverita de azúcar a festejar con nosotros el día de muertos. 
                                 Ella viene preparada con sus leyendas mexicanas favoritas: La mulata de Córdova, La muerte de la 
                                 madrina, El pelón y la muerte, La llorona. Así, entre risas y leyendas de muertos y aparecidos se 
                                 recuerda a los que ya se han ido y se festeja lo vivido.`,
                    "area": "Carpa de narraciones.",
                    "horario": "13:00 horas.",
                    "publico": "Para niñas y niños de 6 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "2":{
                    "nombre": "\"¡Tamalero, tamalero: deme mi tamal!\" ",
                    "descripcion": "Narración oral",
                    "tallerista": "Juan Carlos Jiménez",
                    "sinopsis": `Ofrenda de cuentos, calaveritas y canciones para nuestros difuntos.`,
                    "area": "Carpa de narraciones.",
                    "horario": "14:00 horas.",
                    "publico": "Para niñas y niños de 6 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "3":{
                    "nombre": "\"La Catrina viaja por el mundo\" ",
                    "descripcion": "Narración oral",
                    "tallerista": "Ana Cristina Ortega",
                    "sinopsis": `Desde el más allá viene la dulce calaverita de azúcar a festejar con nosotros el día de muertos. 
                                 Ella viene preparada con sus leyendas mexicanas favoritas: La mulata de Córdova, La muerte de la 
                                 madrina, El pelón y la muerte, La llorona. Así, entre risas y leyendas de muertos y aparecidos se 
                                 recuerda a los que ya se han ido y se festeja lo vivido.`,
                    "area": "Carpa de narraciones.",
                    "horario": "15:00 horas.",
                    "publico": "Para niñas y niños de 6 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "4":{
                    "nombre": "\"La muerte fuerte y gorda\" ",
                    "descripcion": "Narración oral",
                    "tallerista": "Selene de la Cruz",
                    "sinopsis": ``,
                    "area": "Carpa de narraciones.",
                    "horario": "16:00 horas.",
                    "publico": "Para niñas y niños de 6 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
            },
        },
        "videos":{
            "1":{
                "nombre": "Feria de las calacas 2018",
                "url": "https://www.youtube.com/watch?v=yPXUyucEOMg",
            },
            "2":{
                "nombre": "XVI Feria de las Calacas de Alas y Raíces",
                "url": "https://www.youtube.com/watch?v=FpzX8JpTHLI",
            },
            "3":{
                "nombre": "Feria de las calacas 2015",
                "url": "https://www.youtube.com/watch?v=qbKAQHzK8aw",
            },
        }
    },
    "ecatepec": {
        "sede": "Deportivo “Alfredo del Mazo”",
        "horarios": "de 12:00pm a 17:00pm",
        "direccion": "Guanajuato 33, col. Jardines de Morelos 5° Sección, Ecatepec de Morelos, Edo. Mex., C.P. 55450",
        "mapOverview": "img/calaveras/mapaEcatepec.JPG",
        "mapLink": "https://www.google.com/maps/place/Deportivo+Alfredo+Del+Mazo/@19.5907684,-99.0268162,16.22z/data=!4m5!3m4!1s0x85d1f1c5a016a47b:0x73bf1468c62ce890!8m2!3d19.5935811!4d-99.0267763?hl=es-ES",
        "webLink": "",
        "programa": "img/calaveras/programa.pdf",
        "actividades": {
            "Laboratorios creativos": {
                "1":{
                    "nombre": "\"Versarte: primeros versos entre recuerdos\" ",
                    "descripcion": "Talleres para la primera infancia",
                    "tallerista": "Ruth Galicia",
                    "sinopsis": `Para disfrutar con la Calaca, tilica y flaca, entre versos de calaveritas de azúcar y leche. En 
                                 el marco de la celebración de Día de Muertos, como parte de la recuperación de la tradición y celebrando 
                                 la memoria, niñas y niños de la primera infancia cantan, bailan, y leen calaveritas.`,
                    "area": "Carpas de talleres en canchas.",
                    "horario": "12:00 y 13:00 horas.",
                    "publico": "Para bebés de 0 a 24 meses, acompañados por un adulto.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "2":{
                    "nombre": "\"Versarte: primeros versos entre recuerdos\" ",
                    "descripcion": "Talleres para la primera infancia",
                    "tallerista": "Ruth Galicia",
                    "sinopsis": `Para disfrutar con la Calaca, tilica y flaca, entre versos de calaveritas de azúcar y leche. En 
                                 el marco de la celebración de Día de Muertos, como parte de la recuperación de la tradición y celebrando 
                                 la memoria, niñas y niños de la primera infancia cantan, bailan, y leen calaveritas.`,
                    "area": "Carpas de talleres en canchas.",
                    "horario": "15:00 y 16:00 horas.",
                    "publico": "Para niños y niñas de 3 a 5 años, acompañados por un adulto.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "3":{
                    "nombre": "\"Vestidos para la ofrenda\" ",
                    "descripcion": "Talleres para la segunda infancia",
                    "tallerista": "Adriana Ruíz",
                    "sinopsis": `Es un breve taller de vestuario en papel y tela donde diseñarán un atuendo para ir a la ofrenda de Día de 
                                 Muertos.`,
                    "area": "Carpas de talleres en canchas.",
                    "horario": "12: 00, 13:00, 15:00 y 16:00 horas.",
                    "publico": "Para niños y niñas de 6 a 12 años de edad.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "4":{
                    "nombre": "\"Viaje a Mictlán\" ",
                    "descripcion": "Talleres para la segunda infancia",
                    "tallerista": "Oliver Miranda y Nancy Daniela",
                    "sinopsis": `Actividad de exploración sensorial y literaria. A partir de la narración del libro “El Viaje a Mictlán” 
                                 de Víctor José Palacios, los participantes recorrerán los nueve niveles, descubriendo los lugares y pasajes 
                                 contados de manera sensorial y auditiva, antes de llegar al Mictlán.`,
                    "area": "Carpas de talleres en canchas.",
                    "horario": "12: 00, 13:00, 15:00 y 16:00 horas.",
                    "publico": "Para niños y niñas de 6 a 12 años de edad.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "5":{
                    "nombre": "\"Calaca Fanzine\" ",
                    "descripcion": "Talleres para Adolescentes",
                    "tallerista": "Diana Gutiérrez",
                    "sinopsis": `A los participantes, realizarán fanzines para la difusión de ideas. Recordarán a sus muertos y les escribirán.`,
                    "area": "Carpas de talleres en canchas.",
                    "horario": "12: 00, 13:00, 15:00 y 16:00 horas.",
                    "publico": "Para adolescentes de 13 a 17 años de edad.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "6":{
                    "nombre": "\"Gráfica y collage con papeles olvidados\" ",
                    "descripcion": "Talleres para Adolescentes",
                    "tallerista": "Tere Valencia",
                    "sinopsis": `Los participantes dialogarán sobre la huella que dejan muchas personas al irse de esta Tierra. Y con técnicas 
                                 de estampado, collage, dibujo; deriva y lecturas, los asistentes identificarán, explorarán e intervendrán de 
                                 manera gráfica papeles de distintos usos, para generar sus propias narrativas gráficas, derivadas en piezas de 
                                 gráfica y un libro de viaje.`,
                    "area": "Carpas de talleres en canchas.",
                    "horario": "12: 00, 13:00, 15:00 y 16:00 horas.",
                    "publico": "Para adolescentes de 13 a 17 años de edad.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
            },
            "Presentaciones artísticas": {
                "1":{
                    "nombre": "\"Los Botes Cantan pa’ los muertitos.\" ",
                    "descripcion": "Música",
                    "tallerista": "Los Botes Cantan",
                    "sinopsis": `Que se preparen los muertitos y los vivos, Los Botes Cantan vienen con mucha música para Día de Muertos.`,
                    "area": "Escenario principal.",
                    "horario": "12:00 horas.",
                    "publico": "A partir de 4 años.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "2":{
                    "nombre": "\"De calaveras y otras cosas.\" ",
                    "descripcion": "Música tradicional mexicana",
                    "tallerista": "Nesh-Kala",
                    "sinopsis": `La música y la letra hacen un recorrido desde la tradición indígena, con un poema en lengua náhuatl, pasando 
                                 por la tradición mestiza con canciones como la Llorona, hasta llegar al México contemporáneo, en donde se 
                                 aprecia como es un velorio en una vecindad.`,
                    "area": "Escenario principal.",
                    "horario": "14:00 horas.",
                    "publico": "Para toda la familia.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "3":{
                    "nombre": "\"¡Música y matraca para la calaca!.\" ",
                    "descripcion": "Música",
                    "tallerista": "Valentina Barrios y Los Indómitos",
                    "sinopsis": `Entre risas, misterio y terror, moveremos los huesos con historias de amor; así, entre cuento, cuento y 
                                 mucha canción, aparecerá una ofrenda a todo color.`,
                    "area": "Escenario principal.",
                    "horario": "16:00 horas.",
                    "publico": "A partir de 6 años.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "4":{
                    "nombre": "\"Cuando la muerte sea rima: La Catrina vs El Nahual.\" ",
                    "descripcion": "Música tradicional y contemporánea/Controversia",
                    "tallerista": "",
                    "sinopsis": `De dos a tres caídas con límite de tiempo, una batalla de versos con los más terroríficos de ultratumba: 
                                 en una esquina La Catrina del bando de los técnicos y en la otra esquina El Nahual del bando de los 
                                 rudos.
                                 Aquí puedes participar con ellos… ¿Y tú, de qué bando eres?`,
                    "area": "Escenario principal.",
                    "horario": "17:20 a 18:00 horas.",
                    "publico": "Para toda la familia.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
            },
            "Exposiciones": {
                "1":{
                    "nombre": "\"Ofrenda Comunidad.\" ",
                    "descripcion": "Ofrenda propuesta por locatarios de Ecatepec",
                    "tallerista": "Alas y Raíces",
                    "sinopsis": `Ofrenda por locatarios e instancias participantes.`,
                    "area": "",
                    "horario": "De 11:00 a 18:00 horas.",
                    "publico": "Para Infancias, público juvenil y público en general.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
            },
            "Narraciones orales": {
                "1":{
                    "nombre": "\"Aluxes y otros espantos.\" ",
                    "descripcion": "Narración oral",
                    "tallerista": "Astrid Perellón",
                    "sinopsis": `En la fiesta anual de monstruos, el aluxe maya se sintió enormemente ofendido por no ser invitado. 
                                 ¿Será tan espantoso como para arruinar la fiesta?`,
                    "area": "Carpa de narraciones. Deportivo de la Siervo",
                    "horario": "13:00 horas.",
                    "publico": "Para niñas y niños de 6 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "2":{
                    "nombre": "\"El compadre de la muerte y otras calacas.\" ",
                    "descripcion": "Narración oral",
                    "tallerista": "Nacho Casas",
                    "sinopsis": `A partir de El compadre de la muerte, leyenda mexicana que ha inspirado cuentos, novelas y hasta una película, 
                                 viajamos a través de diversas tradiciones de nuestro país que festejan, temen y juegan con la huesuda. 
                                 Continuamos con Jack y la muerte, relato donde un niño se enfrenta a la calaca hasta hacerla desistir de su 
                                 propósito y concluimos con El pesero fantasma, divertimento, donde un difunto chofer de microbuses recorre las 
                                 avenidas de la Ciudad de México.`,
                    "area": "Carpa de narraciones. Deportivo de la Siervo",
                    "horario": "14:00 horas.",
                    "publico": "Para niñas y niños de 6 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "3":{
                    "nombre": "\"No me llores. Homenaje a las abuelas sabias.\" ",
                    "descripcion": "Narración oral",
                    "tallerista": "Florina Piña",
                    "sinopsis": `Homenaje a las abuelas sabias entre la tradición oral y la literatura.`,
                    "area": "Carpa de narraciones. Deportivo de la Siervo",
                    "horario": "15:00 horas.",
                    "publico": "Para niñas y niños de 6 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
                "4":{
                    "nombre": "\"Que la memoria no muera.\" ",
                    "descripcion": "Narración oral",
                    "tallerista": "Benjamín Briseño",
                    "sinopsis": `Tradición oral para recordar.`,
                    "area": "Carpa de narraciones. Deportivo de la Siervo",
                    "horario": "16:00 horas.",
                    "publico": "Para niñas y niños de 6 años en adelante.",
                    "observaciones": "",
                    "delegacion": "" ,
                },
            },
        },
        "videos":{
            "1":{
                "nombre": "Feria de las calacas 2018",
                "url": "https://www.youtube.com/watch?v=yPXUyucEOMg",
            },
            "2":{
                "nombre": "XVI Feria de las Calacas de Alas y Raíces",
                "url": "https://www.youtube.com/watch?v=FpzX8JpTHLI",
            },
            "3":{
                "nombre": "Feria de las calacas 2015",
                "url": "https://www.youtube.com/watch?v=qbKAQHzK8aw",
            },
        }
    }
}